### ISSUE TITLE
"Field 'serviceUsername_id' doesn't have a default value"

### ISSUE THREAD

**Issue by luissian** [BU-ISCIII/iSkyLIMS-drylab#10]
When the creating a new service . /drylab/service_request_internal_sequencing'
 Error page is showed with : 
"Field 'serviceUsername_id' doesn't have a default value"

**Comment by jlgarciapacheco** [comment]
Hi Luis,
the current version of the code features "serviceUserId" instead of "serviceUsername". Have you performed a git fetch/git pull + makemigrations + migrate?

**Comment by luissian** [comment]
Yes . It was done 
git fetch/git pull + makemigrations + migrate
After that I faced the same issues that we got in Flavia.
I would like to check in Flavia to see if the same problem occur.

**Comment by jlgarciapacheco** [comment]
Luis,
(sorry if you' ve already done this :)) but can you perform a 'grep -r serviceUsername' en /srv/iSkyLIMS/drylab to see where/how you see that field? (just wondering if you have migrations files not updated...).

**Comment by saramonzon** [comment]
Luis, in Flavia works fine. It seems to me you have former serviceUsername field in your local database. I think you should drop it.

**Comment by luissian** [comment]
It is not an issue, but a bug on my laptop.
Thanks for your support
