### ISSUE TITLE
Creating new account issues

### ISSUE THREAD

**Issue by MiguelJulia** [BU-ISCIII/iSkyLIMS-drylab#15]
If you submit an incorrect new account form, there is a broken link to the image it is supposed to be shown. Happened when "passsword1 != password2".

Also, passwords requisites include "Your password can't be a commonly used password" and "Your password can't be too similar to your other personal information". Is this being checked at all? Dummy passwords as "password1234" are still accepted.

**Comment by saramonzon** [comment]
Fixed
