### ISSUE TITLE
Issues modifying account details

### ISSUE THREAD

**Issue by MiguelJulia** [BU-ISCIII/iSkyLIMS-drylab#16]
Same broken link image as when creating new account.

When modifying your account details, you are asked to modify your password too.

Old password can be updated to the same password. This can be a security issue if in the future users are asked to change their passwords periodically or after a security breach.

After modifying your account details, you are not redirected to the previous page, nor the home page.

After modifying your account details, you are automatically logged out.

**Comment by saramonzon** [comment]
Fixed
