### ISSUE TITLE
Drylab/manage services/pending services: Information about status "approved" seems to be useless for user (after introduction of the request, this is in state 'recorded' and, next, it passes to 'queued' or is 'rejected')

### ISSUE THREAD

**Issue by jlgarciapacheco** [BU-ISCIII/iSkyLIMS-drylab#22]
Ponder whether to purge it from the information provided to the user (the "list of services in Approved State" and within the pie chart graph)

**Comment by luissian** [comment]
Solved.
In the last version of the code under pending services are not showed the services on approved state.
